# Generated by Django 3.1.3 on 2022-05-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meubels', '0002_auto_20220524_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='producten',
            name='afmeting_oppervlakte',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bestellingen',
            name='afgerond',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bestellingen',
            name='datum',
            field=models.DateTimeField(default='1970-01-01 00:00'),
        ),
        migrations.AlterField(
            model_name='bestellingen',
            name='datum_afgerond',
            field=models.DateTimeField(default='1970-01-01 00:00'),
        ),
        migrations.AlterField(
            model_name='bestellingen',
            name='prijs_totaal',
            field=models.FloatField(default=0),
        ),
    ]
