# Generated by Django 3.1.3 on 2022-05-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meubels', '0004_kamerafmetingen_afmeting_oppervlakte'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellingen',
            name='datum_tot',
            field=models.DateTimeField(default='1970-01-01 00:00'),
        ),
    ]
