# Generated by Django 3.1.3 on 2022-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meubels', '0005_bestellingen_datum_tot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellingen',
            name='afstand',
            field=models.IntegerField(default=0),
        ),
    ]
