# Generated by Django 3.1.3 on 2022-05-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meubels', '0006_bestellingen_afstand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellingen',
            name='prijs_maand',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bestellingen',
            name='prijs_verzending',
            field=models.FloatField(default=0),
        ),
    ]
