# Generated by Django 3.1.3 on 2022-05-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meubels', '0007_auto_20220525_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellingen',
            name='datum_tot',
            field=models.DateTimeField(default='2022-01-01 00:00'),
        ),
    ]
